# formato de documentos para docker, crud_db imagen 
# hacer una aplicacion, entregar video (minimo de 10 minutos), readme.md (Descripcion tecnica y flujo del sistema)
# subir el codigo por github
# la aplicacion sobre un dashboard de el check de veiculos de transporte (bicitaxis) inventario de veiculos 
# sttcht withgoogle
# con note, contenedores, separar parte publica y privada, controladores de la ruta separados, separar back de front en carpetitas
# con la estructura tecnica y el flujo del desarrollo de mi programa (esto se lo pides a la ia para que mejore el readme)
